fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

atelier_core:
    resource: "@AtelierCoreBundle/Resources/config/routing.yml"
    prefix:   /

atelier_user:
    resource: "@AtelierUserBundle/Resources/config/routing.yml"
    prefix:   /
